name: Update Doc

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14
    - name: Build with Maven
      run: cd ./render && mvn compile
    - name: update doc
      run: cd ./render && mvn exec:java  -Dlog4j.skipJansi=false -Dexec.mainClass=ikas.project.java.ms.App 
    - name: set git env
      env:
          ACTION_DEPLOY_KEY: ${{secrets.SAKIX}}
      run: |
          mkdir -p ~/.ssh/
          echo "$ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.name "Actions"
          git config --global user.email "Actions"
    - name: commit
      run: | 
          remote remove "origin"
          remote add "origin" "git@github.com:ikas-mc/ms-store-app-repo.git"	
          git commint -m "Github Actions Update Doc" 
          git push  
      
